name: Juno_env
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=5.3.0
  - altair-all=5.3.0
  - dash=2.16.1
  - dash-bootstrap-components=1.5.0
  - geopandas=0.14.3
  - ipykernel=6.29.3
  - ipython=8.22.2
  - matplotlib=3.8.4
  - numpy=1.26.4
  - pandas=2.2.2
  - plotly=5.19.0
  - python=3.12.2
  - scikit-learn=1.4.2
  - seaborn=0.13.2
  - pyarrow=15.0.2
  - fastparquet=2024.2.0
  - pip:
      - dash-vega-components==0.10.0
