name: 532_project_env
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.8
  - pandas=1.3.3
  - numpy=1.21.2
  - matplotlib=3.4.3
  - seaborn=0.11.2
  - plotly=5.3.1
  - dash-bootstrap-components=1.5.0
  - ipykernel=6.29.3
  - altair-all=5.3.0
  - dash=2.16.1
  - dash-vega-components=0.9.0 
  - geopandas
